### ISSUE TITLE
JS Promise rejections should use `new Error()` equivalent instead of string 

### ISSUE THREAD

**Issue by trevyn** [trevyn/turbocharger#1]
Provides better backtrace info, see e.g.:

- https://github.com/rustwasm/wasm-bindgen/issues/1742
- https://stackoverflow.com/questions/591857/how-can-i-get-a-javascript-stack-trace-when-i-throw-an-exception

**Comment by Zishan-7** [comment]
So, this needs to be changed everywhere in the whole codebase,right?

**Comment by trevyn** [comment]
I think it's just here:

https://github.com/trevyn/turbocharger/blob/ee2d1d6273686ab43f3d7e5d53e8bcc7b57c874f/turbocharger-impl/src/lib.rs#L146-L150

but the trick is that it's generated in Rust as a `wasm-bindgen` `JsValue`. Also, `maybe_map_err` is used in two places, one of which needs to remain a string, so it'll need to be split in two.
